config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :sessions, only: [:create, :destroy]
  root 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  delete '/logout' => 'sessions#destroy', as: :logout

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :project_name,        presence: true
  validates :project_place,       presence: true
  validates :start_time,          presence: true
  validates :end_time,            presence: true
  validates :content,             presence: true
  validates :company_name,        presence: true
  validates :company_owner_name,  presence: true
  validate :start_time_should_be_before_end_time

  private

  def start_time_should_be_before_end_time
    return unless start_time && end_time

    if start_time >= end_time
      errors.add(:start_time, '終了時間よりも前に設定してください')
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :projects
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    
    unless user
      user = User.create(
      	uid: auth.uid,
      	provider: auth.provider,
      	email: User.dummy_email(auth),
      	password: Devise.friendly_token[0, 20]
      	)
    end
    user
  end

  private

  def self.dummy_email(auth)
  	"#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?

  private

  def logged_in?
  	!!session[:user_id]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: '作成しました'
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

private

  def project_params
    params.require(:project).permit(:project_name, :project_place, :start_time, :end_time, :content, :company_name, :company_owner_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged in'
　end
　
  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end
  
  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'nitro'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "nitro", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Make Project", new_project_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Logout", logout_path %></li>
            <% else %>
          　  <li><%= link_to "Login", user_omniauth_authorize_path(:facebook) %></li>
            <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
   <%= render 'layouts/header' %> 
   <div class="container">
    <%= yield %>
   </div>
  </body>
 </html> 

app/views/projects/new.html.erb
<% now = Time.zone.now %>

<div class="page-header">
  <h1>プロジェクト作成</h1>
</div>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@project) do |f| %>

　　<div class="form-group">
    <%= f.label :project_name　%>
    <%= f.text_field :project_name %>

    <%= f.label :project_place %>
    <%= f.text_field :project_place %>

    <%= f.label :start_time %>
    <%= f.datetime_select :start_time, start_year: now.year, end_year: now.year + 1 %>

    <%= f.label :end_time %>
    <%= f.datetime_select :end_time, start_year: now.year, end_year: now.year + 1 %>

    <%= f.label :content %>
    <%= f.text_area :content %>

    <%= f.label :company_name %>
    <%= f.text_field :company_name %>

    <%= f.label :company_owner_name %>
    <%= f.text_field :company_owner_name %>

    <%= f.submit "make project", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="center here-unit">
 <h1>Welcome</h1>
　　
</div>